package manifest

import (
	"sort"
	"testing"

	"github.com/colibrisec/ojo/internal/model"
)

// nameVersions flattens pkgs to sorted "name@version" strings, so a test can
// compare against a parser whose output order follows map iteration.
func nameVersions(pkgs []model.Package) []string {
	out := make([]string, 0, len(pkgs))
	for _, p := range pkgs {
		out = append(out, p.Name+"@"+p.Version)
	}
	sort.Strings(out)
	return out
}

func assertPackages(t *testing.T, pkgs []model.Package, eco model.Ecosystem, want ...string) {
	t.Helper()
	got := nameVersions(pkgs)
	sort.Strings(want)
	if len(got) != len(want) {
		t.Fatalf("got %v, want %v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("got %v, want %v", got, want)
		}
	}
	for _, p := range pkgs {
		if p.Ecosystem != eco {
			t.Errorf("%s: ecosystem %q, want %q", p.Name, p.Ecosystem, eco)
		}
	}
}

func TestUvLockParser(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "uv.lock", `version = 1
requires-python = ">=3.12"

[[package]]
name = "myapp"
version = "0.1.0"
source = { virtual = "." }
dependencies = [
    { name = "requests" },
]

[[package]]
name = "shared-lib"
version = "0.2.0"
source = { editable = "libs/shared" }

[[package]]
name = "requests"
version = "2.31.0"
source = { registry = "https://pypi.org/simple" }
sdist = { url = "https://files.pythonhosted.org/requests-2.31.0.tar.gz", hash = "sha256:abc", size = 1 }

[[package]]
name = "forked"
version = "1.4.0"
source = { git = "https://github.com/example/forked?rev=abc#abc" }
`)

	pkgs, err := uvLockParser{}.Parse(dir + "/uv.lock")
	if err != nil {
		t.Fatal(err)
	}
	// The project itself and an editable workspace member aren't published
	// packages; a git dependency still has a name and version worth checking.
	assertPackages(t, pkgs, model.EcosystemPyPI, "requests@2.31.0", "forked@1.4.0")
}

func TestPdmLockParser(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "pdm.lock", `[metadata]
groups = ["default"]
lock_version = "4.5.0"
content_hash = "sha256:abc"

[[package]]
name = "certifi"
version = "2024.2.2"
requires_python = ">=3.6"
summary = "Python package for providing Mozilla's CA Bundle."
files = [
    {file = "certifi-2024.2.2-py3-none-any.whl", hash = "sha256:abc"},
]

[[package]]
name = "idna"
version = "3.6"
`)

	pkgs, err := pdmLockParser{}.Parse(dir + "/pdm.lock")
	if err != nil {
		t.Fatal(err)
	}
	assertPackages(t, pkgs, model.EcosystemPyPI, "certifi@2024.2.2", "idna@3.6")
}

func TestYarnLockParser_Classic(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "yarn.lock", `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/code-frame@^7.0.0", "@babel/code-frame@^7.8.3":
  version "7.8.3"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.8.3.tgz#abc"
  integrity sha512-abc
  dependencies:
    "@babel/highlight" "^7.8.3"

lodash@^4.17.15, lodash@^4.17.20:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#abc"

"string-width-cjs@npm:string-width@^4.2.0":
  version "4.2.3"
  resolved "https://registry.yarnpkg.com/string-width/-/string-width-4.2.3.tgz#abc"

"local-thing@file:../local-thing":
  version "1.0.0"
`)

	pkgs, err := yarnLockParser{}.Parse(dir + "/yarn.lock")
	if err != nil {
		t.Fatal(err)
	}
	// The nested `"@babel/highlight" "^7.8.3"` dependency line must not be
	// read as an entry; the alias resolves to the real package name.
	assertPackages(t, pkgs, model.EcosystemNpm, "@babel/code-frame@7.8.3", "lodash@4.17.21", "string-width@4.2.3")
}

func TestYarnLockParser_Berry(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "yarn.lock", `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"@babel/code-frame@npm:^7.0.0, @babel/code-frame@npm:^7.8.3":
  version: 7.8.3
  resolution: "@babel/code-frame@npm:7.8.3"
  dependencies:
    "@babel/highlight": "npm:^7.8.3"
  checksum: 10c0/abc
  languageName: node
  linkType: hard

"lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  languageName: node
  linkType: hard

"string-width-cjs@npm:string-width@^4.2.0":
  version: 4.2.3
  resolution: "string-width@npm:4.2.3"
  languageName: node
  linkType: hard

"myapp@workspace:.":
  version: 0.0.0-use.local
  resolution: "myapp@workspace:."
  languageName: unknown
  linkType: soft
`)

	pkgs, err := yarnLockParser{}.Parse(dir + "/yarn.lock")
	if err != nil {
		t.Fatal(err)
	}
	assertPackages(t, pkgs, model.EcosystemNpm, "@babel/code-frame@7.8.3", "lodash@4.17.21", "string-width@4.2.3")
}

func TestPnpmLockParser(t *testing.T) {
	cases := map[string]string{
		"v5": `lockfileVersion: 5.4

packages:

  /@babel/core/7.0.0:
    resolution: {integrity: sha512-abc}
    dev: false

  /lodash/4.17.21:
    resolution: {integrity: sha512-abc}

  /react-dom/17.0.2_react@17.0.2:
    resolution: {integrity: sha512-abc}
`,
		"v6": `lockfileVersion: '6.0'

packages:

  /@babel/core@7.0.0:
    resolution: {integrity: sha512-abc}

  /lodash@4.17.21:
    resolution: {integrity: sha512-abc}

  /react-dom@17.0.2(react@17.0.2):
    resolution: {integrity: sha512-abc}
`,
		"v9": `lockfileVersion: '9.0'

importers:

  .:
    dependencies:
      lodash:
        specifier: ^4.17.21
        version: 4.17.21

packages:

  '@babel/core@7.0.0':
    resolution: {integrity: sha512-abc}

  lodash@4.17.21:
    resolution: {integrity: sha512-abc}

  react-dom@17.0.2:
    resolution: {integrity: sha512-abc}

  forked@https://codeload.github.com/example/forked/tar.gz/abc:
    resolution: {tarball: https://codeload.github.com/example/forked/tar.gz/abc}

snapshots:

  react-dom@17.0.2(react@17.0.2):
    dependencies:
      react: 17.0.2
`,
	}
	for name, content := range cases {
		t.Run(name, func(t *testing.T) {
			dir := t.TempDir()
			write(t, dir, "pnpm-lock.yaml", content)
			pkgs, err := pnpmLockParser{}.Parse(dir + "/pnpm-lock.yaml")
			if err != nil {
				t.Fatal(err)
			}
			assertPackages(t, pkgs, model.EcosystemNpm, "@babel/core@7.0.0", "lodash@4.17.21", "react-dom@17.0.2")
		})
	}
}

func TestPodfileLockParser(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "Podfile.lock", `PODS:
  - Alamofire (5.9.1)
  - Firebase/Core (10.24.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 10.24.0)
  - Firebase/CoreOnly (10.24.0):
    - FirebaseCore (= 10.24.0)
  - FirebaseCore (10.24.0)

DEPENDENCIES:
  - Alamofire (~> 5.9)
  - Firebase/Core

SPEC REPOS:
  trunk:
    - Alamofire
    - Firebase

SPEC CHECKSUMS:
  Alamofire: abc

PODFILE CHECKSUM: abc

COCOAPODS: 1.15.2
`)

	pkgs, err := podfileLockParser{}.Parse(dir + "/Podfile.lock")
	if err != nil {
		t.Fatal(err)
	}
	// Subspecs collapse into their root pod, reported once.
	assertPackages(t, pkgs, model.EcosystemCocoaPods, "Alamofire@5.9.1", "Firebase@10.24.0", "FirebaseCore@10.24.0")
}

func TestNpmLockParser_ReadsLicense(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "package-lock.json", `{"lockfileVersion": 3, "packages": {
  "": {"name": "app", "version": "1.0.0"},
  "node_modules/left-pad": {"version": "1.3.0", "license": "WTFPL"}
}}`)

	pkgs, err := npmLockParser{}.Parse(dir + "/package-lock.json")
	if err != nil {
		t.Fatal(err)
	}
	if len(pkgs) != 1 || pkgs[0].License != "WTFPL" {
		t.Fatalf("unexpected packages: %+v", pkgs)
	}
}
