package manifest

import "testing"

func TestCargoLockParser(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "Cargo.lock", `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "time"
version = "0.1.42"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "libc",
]

[[package]]
name = "libc"
version = "0.2.0"
`)

	pkgs, err := cargoLockParser{}.Parse(dir + "/Cargo.lock")
	if err != nil {
		t.Fatal(err)
	}
	want := map[string]bool{"time@0.1.42": false, "libc@0.2.0": false}
	for _, p := range pkgs {
		if p.Ecosystem != "crates.io" {
			t.Errorf("expected crates.io ecosystem, got %q", p.Ecosystem)
		}
		want[p.Name+"@"+p.Version] = true
	}
	for k, found := range want {
		if !found {
			t.Errorf("expected package %s not found in %+v", k, pkgs)
		}
	}
}

func TestPoetryLockParser(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "poetry.lock", `[[package]]
name = "requests"
version = "2.28.1"
description = "Python HTTP for Humans."
category = "main"
optional = false
python-versions = ">=3.7, <4.0"

[[package]]
name = "pytest"
version = "7.1.0"
`)

	pkgs, err := poetryLockParser{}.Parse(dir + "/poetry.lock")
	if err != nil {
		t.Fatal(err)
	}
	want := map[string]bool{"requests@2.28.1": false, "pytest@7.1.0": false}
	for _, p := range pkgs {
		if p.Ecosystem != "PyPI" {
			t.Errorf("expected PyPI ecosystem, got %q", p.Ecosystem)
		}
		want[p.Name+"@"+p.Version] = true
	}
	for k, found := range want {
		if !found {
			t.Errorf("expected package %s not found in %+v", k, pkgs)
		}
	}
}
