package misconfig

// ruleCWEs maps each misconfig rule ID to its applicable CWE IDs, most
// relevant first. It's a flat, explicit table rather than a derived lookup
// because rule ID prefixes (cfn-, tf-, tf-azure-, tf-gcp-, k8s-, mcp-,
// skill-, dockerfile-) don't share a common category naming scheme the way
// sast's per-language rule IDs do. A rule absent here (e.g.
// dockerfile-no-healthcheck, tf-lambda-no-xray-tracing) is a reliability/
// hygiene check with no real CWE fit; newIssue leaves CWEs unset for it.
var ruleCWEs = map[string][]string{
	"dockerfile-secret-env": {"CWE-798"},

	"cfn-s3-public-acl":                     {"CWE-284"},
	"cfn-s3-missing-public-access-block":    {"CWE-284"},
	"cfn-s3-public-access-block-incomplete": {"CWE-284"},
	"cfn-rds-publicly-accessible":           {"CWE-284"},
	"cfn-lb-internet-facing":                {"CWE-284"},
	"tf-s3-public-acl":                      {"CWE-284"},
	"tf-s3-missing-public-access-block":     {"CWE-284"},
	"tf-s3-public-access-block-incomplete":  {"CWE-284"},
	"tf-lb-internet-facing":                 {"CWE-284"},
	"tf-redshift-publicly-accessible":       {"CWE-284"},
	"tf-eks-public-endpoint":                {"CWE-284"},
	"tf-azure-storage-container-public":     {"CWE-284"},
	"tf-azure-storage-public-blob-access":   {"CWE-284"},
	"tf-azure-storage-network-open":         {"CWE-284"},
	"tf-azure-cosmosdb-public-access":       {"CWE-284"},
	"tf-azure-sql-public-access":            {"CWE-284"},
	"tf-azure-keyvault-network-open":        {"CWE-284"},
	"tf-azure-aks-public-api":               {"CWE-284"},
	"tf-azure-acr-public-access":            {"CWE-284"},
	"tf-azure-aks-no-network-policy":        {"CWE-284"},
	"tf-gcp-cloudsql-public-ip":             {"CWE-284"},
	"tf-gcp-compute-public-ip":              {"CWE-284"},
	"tf-gcp-iam-public-member":              {"CWE-284"},
	"tf-gcp-gke-not-private":                {"CWE-284"},
	"tf-gcp-gke-no-authorized-networks":     {"CWE-284"},
	"tf-gcp-gke-no-network-policy":          {"CWE-284"},
	"tf-gcp-gcs-no-uniform-access":          {"CWE-284"},
	"tf-security-group-open-ingress":        {"CWE-284"},
	"tf-security-group-open-egress":         {"CWE-284"},
	"tf-azure-nsg-open-inbound":             {"CWE-284"},
	"tf-gcp-firewall-open-ingress":          {"CWE-284"},

	"tf-apigateway-method-no-auth":   {"CWE-306"},
	"tf-lambda-function-url-no-auth": {"CWE-306"},

	"k8s-privileged-container":       {"CWE-250"},
	"k8s-allow-privilege-escalation": {"CWE-250"},
	"k8s-run-as-root":                {"CWE-250"},
	"tf-ecs-privileged-container":    {"CWE-250"},
	"dockerfile-root-user":           {"CWE-250"},

	"cfn-iam-wildcard-policy":        {"CWE-269"},
	"tf-iam-wildcard-policy":         {"CWE-269"},
	"tf-iam-s3-wildcard-policy":      {"CWE-269"},
	"tf-iam-passrole-unrestricted":   {"CWE-269"},
	"tf-iam-policy-attached-to-user": {"CWE-269"},
	"tf-gcp-compute-broad-scope":     {"CWE-269"},
	"tf-gcp-gke-legacy-abac":         {"CWE-269"},
	"tf-azure-acr-admin-enabled":     {"CWE-269"},
	"mcp-auto-approve-wildcard":      {"CWE-269"},
	"skill-broad-tool-permissions":   {"CWE-269"},

	"tf-iam-weak-password-policy": {"CWE-521"},

	"cfn-s3-unencrypted":                   {"CWE-311"},
	"cfn-rds-unencrypted":                  {"CWE-311"},
	"tf-s3-unencrypted":                    {"CWE-311"},
	"tf-efs-unencrypted":                   {"CWE-311"},
	"tf-ebs-root-volume-unencrypted":       {"CWE-311"},
	"tf-redshift-unencrypted":              {"CWE-311"},
	"tf-elasticache-not-encrypted-at-rest": {"CWE-311"},
	"tf-kinesis-not-encrypted":             {"CWE-311"},
	"tf-sns-unencrypted":                   {"CWE-311"},
	"tf-cloudwatch-log-group-unencrypted":  {"CWE-311"},
	"tf-unencrypted-storage":               {"CWE-311"},

	"cfn-kms-rotation-disabled":           {"CWE-320"},
	"tf-kms-rotation-disabled":            {"CWE-320"},
	"tf-gcp-kms-no-rotation":              {"CWE-320"},
	"tf-ecr-not-cmk-encrypted":            {"CWE-320"},
	"tf-sqs-not-cmk":                      {"CWE-320"},
	"tf-secretsmanager-not-cmk":           {"CWE-320"},
	"tf-cloudtrail-not-cmk":               {"CWE-320"},
	"tf-rds-performance-insights-not-cmk": {"CWE-320"},
	"tf-gcp-pubsub-not-cmek":              {"CWE-320"},

	"tf-lb-listener-plain-http":               {"CWE-319"},
	"tf-cloudfront-plain-http":                {"CWE-319"},
	"tf-azure-appservice-http-allowed":        {"CWE-319"},
	"tf-azure-storage-insecure-transport":     {"CWE-319"},
	"tf-azure-redis-non-ssl":                  {"CWE-319"},
	"tf-azure-db-ssl-disabled":                {"CWE-319"},
	"tf-gcp-cloudsql-ssl-not-required":        {"CWE-319"},
	"tf-elasticache-not-encrypted-in-transit": {"CWE-319"},
	"mcp-plaintext-transport":                 {"CWE-319"},

	"tf-azure-appservice-weak-tls": {"CWE-326"},
	"tf-azure-sql-weak-tls":        {"CWE-326"},
	"tf-azure-storage-weak-tls":    {"CWE-326"},
	"tf-azure-redis-weak-tls":      {"CWE-326"},
	"tf-cloudfront-weak-tls":       {"CWE-326"},

	"mcp-cross-origin-credential": {"CWE-346"},
	"tf-rds-iam-auth-disabled":    {"CWE-287"},

	"cfn-imdsv1-enabled": {"CWE-918"},
	"tf-imdsv1-enabled":  {"CWE-918"},

	"cfn-cloudtrail-no-log-validation": {"CWE-778"},
	"cfn-cloudtrail-not-multi-region":  {"CWE-778"},
	"tf-cloudtrail-no-log-validation":  {"CWE-778"},
	"tf-cloudtrail-not-multi-region":   {"CWE-778"},
	"tf-s3-logging-disabled":           {"CWE-778"},
	"tf-cloudfront-no-logging":         {"CWE-778"},
	"tf-apigateway-no-access-logging":  {"CWE-778"},
	"tf-eks-no-control-plane-logging":  {"CWE-778"},
	"tf-vpc-no-flow-log":               {"CWE-778"},
	"tf-guardduty-disabled":            {"CWE-778"},

	"cfn-dynamodb-pitr-disabled":            {"CWE-693"},
	"cfn-s3-versioning-disabled":            {"CWE-693"},
	"tf-dynamodb-pitr-disabled":             {"CWE-693"},
	"tf-s3-versioning-disabled":             {"CWE-693"},
	"tf-gcp-gcs-no-versioning":              {"CWE-693"},
	"tf-gcp-cloudsql-no-backups":            {"CWE-693"},
	"tf-cloudfront-no-waf":                  {"CWE-693"},
	"tf-azure-keyvault-no-purge-protection": {"CWE-693"},
	"tf-gcp-compute-no-shielded-vm":         {"CWE-693"},

	"k8s-missing-resource-limits": {"CWE-400"},
	"tf-ecs-no-readonly-root-fs":  {"CWE-732"},

	"cfn-ecr-tag-mutable":            {"CWE-494"},
	"tf-ecr-tag-mutable":             {"CWE-494"},
	"dockerfile-add-instead-of-copy": {"CWE-494"},
	"skill-fetch-execute":            {"CWE-494"},

	"dockerfile-latest-tag":      {"CWE-829"},
	"tf-ami-no-owners":           {"CWE-829"},
	"mcp-remote-server-unpinned": {"CWE-829"},
	"mcp-unpinned-launcher":      {"CWE-829"},

	"mcp-hidden-unicode":   {"CWE-506"},
	"skill-hidden-unicode": {"CWE-506"},

	"mcp-prompt-injection-language":   {"CWE-1427"},
	"skill-prompt-injection-language": {"CWE-1427"},

	"mcp-shell-wrapper":                {"CWE-78"},
	"skill-credential-exfil-reference": {"CWE-522"},
	"tf-alb-invalid-headers-allowed":   {"CWE-444"},
}
