name: ci
on:
  push:
    branches: [main]
  pull_request: {}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      pull-requests: write
      statuses: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: "1.26"
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test -coverprofile=coverage.out -covermode=atomic ./...
      - name: Coverage report
        uses: getsentry/codecov-action@5f3f449cf9e909fd63513a48f27c57f090a5f321 # v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          post-pr-comment: true
      - name: Build
        run: go build ./...

  coverage-badge:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: "1.26"
      - name: Test
        run: go test -v ./...
      - name: Update coverage report
        uses: ncruces/go-coverage-report@dfc237255099f2d25066babde51253992175e365 # v0.3.2
        with:
          report: true
          chart: true
          amend: true
        continue-on-error: true
